config/routes.rb
Rails.application.routes.draw do
  resources :stores, only: [:index] do
    collection { post :import }
  end

  root 'stores#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude, :address => :geocoded_address #save geocoded address, but display will be address privided in file
  after_validation :reverse_geocode  # auto-fetch address

  def full_address
    [address, postal_code].compact.join(', ')
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1).collect {|i| i.downcase} #Headers in tsv file don't have to be all lowercase
    valid_keys = ['name', 'address', 'postal_code', 'latitude', 'longitude']
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      store = find_by_id(row["id"]) || new #find_by_or_initialize
      store.attributes = row.to_hash.slice(*valid_keys)
      store.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".tsv" then Roo::CSV.new(file.path, csv_options: {col_sep: "\t"})
    when ".csv" then Roo::CSV.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    if params[:search].present?
      @base_address = params[:search]
    else
      @base_address = "5973 Avenida Encinas, Carlsbad, CA"
    end
    if params[:radius].present?
      @stores = Store.near(@base_address, params[:radius], :order => "distance").limit(20)
    else
      @stores = Store.near(@base_address, 5, :order => "distance").limit(20)
    end
    @hash = Gmaps4rails.build_markers(@stores) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
    end
  end

  def import
    if Store.import(params[:file])
      redirect_to root_url, notice: "Stores imported."
    else
      redirect_to root_url, notice: "Stores not imported. Please submit .tsv file"
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :address, :postal_code, :latitude, :longitude, :geocoded_address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Caribou Coffee Store Finder
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/stores/index.html.haml
%script{:src => "//maps.google.com/maps/api/js?v=3&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
%script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
.row
  - if flash[:notice]
    .notice.text-center= flash[:notice]
  .import
    %h1.text-center Find a Caribou Coffee Near You!
    %p Submit a tab delimited (.tsv) file showing all stores you'd like to submit. We will return the nearest stores within 5 miles of Verve's Carlsbad office. If you'd like to see stores near another address, search using the address box below.Make sure the table headers are name, address, postal_code, latitude, longitude and includes this information for each store.
    = form_tag import_stores_path, multipart: true do
      = file_field_tag :file
      %br
      = submit_tag "Import"
      %hr
  .search.col-md-8.col-md-offset-2.text-center
    = form_tag stores_path, :method => :get do
      %p
        Type in an address to search for stores near you! You can also search using latitude and longitude coordinates (Ex: 45.2154, -95.0325).
        %br
        %br
        = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Type address or coordinates here'
        %br
        = number_field_tag :radius, params[:radius], class: 'form-control', placeholder: 'Type range (in miles) you would like to search', min: 5
        %br
        %br
        = submit_tag "Search Nearby Stores", :name => nil, class: 'btn btn-default'
        %hr
        -# Add in feature to search nearest with ## miles
  .stores.col-xs-12
    %h3.text-center= "Stores Near #{@base_address}"
    - if @stores.empty?
      %p.text-center= "Sorry, there are no stores near #{@base_address}. Please change your location or search radius, or import new stores to show."
    -else
      %br
      %table.table.table-condensed.table-hover
        %tr
          %th Name
          %th Address
          %th Latitude
          %th Longitude
          %th Distance from Address
        - for store in @stores
          %tr
            %td= store.name
            %td= store.full_address
            %td= store.latitude
            %td= store.longitude
            %td= "#{store.distance.round(2)} miles"
    %hr
  - if @stores.any?
    .col-md-6.col-md-offset-2.text-center{:style => "width: 800px;"}
      %h3 Map View of Nearby Stores
      %br
      #map{:style => "width: 800px; height: 400px;"}
      :javascript
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers(#{raw @hash.to_json});
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });

app/views/stores/index.js.haml
markers = handler.addMarkers(#{raw @hash.to_json});